baseURL = 'https://sripathimanikanta.github.io/itsmaniblog/'
languageCode = 'en-us'
title = "Its Mani's Blog"
theme = 'paper'
author = "Manik Bhasha"
copyright = "© 2024, itsmaniblog.github.io"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'msripathi035'               # twitter.com/YOUR_TWITTER_ID
  github = 'sripathimanikanta'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'manikanta-sripathi-485297194'             # linkedin.com/in/YOUR_LINKEDIN_ID
  monoDarkIcon = true  

  # avatar = 'https://instagram.fhyd7-1.fna.fbcdn.net/v/t51.2885-19/453714428_1233769124467159_9096430823120671256_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_ht=instagram.fhyd7-1.fna.fbcdn.net&_nc_cat=107&_nc_ohc=rM8J7pDVTgIQ7kNvgGxhD7j&_nc_gid=e5fad2428c6748958436d7fee9d0cc5f&edm=AP4sbd4BAAAA&ccb=7-5&oh=00_AYDGn4LkQuzwSUkaLKUtyQ7DZTi2ytZobIs9O66lRP7mFQ&oe=67619FCB&_nc_sid=7a9f4b'
  avatar = 'mani'
  name = 'MANI'
  bio = 'Never stop asking Questions'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10


